const menu = [
  {
    id: 1,
    title: 'እንጀራ ፍርፍር',
    category: 'ቁርስ',
    price: 119.99,
    img: 'https://queenshebabakery.com/wp-content/uploads/2024/10/photo_2024-10-15_08-50-06.jpg',
    desc: `ምርጥ የሀገርኛ ፍርፍር ፥ ከንጹ እንጀራና በቤት ከተዘጋጁ ቅመሞች በእናትነት ፍቅር እና እንክብካቤ የተዘጋጀ።`,
  },
  {
    id: 2,
    title: 'አይነት',
    category: 'ምሳ',
    price: 139.99,
    img: 'https://yaredzemainternationalhotelaxum.com/wp-content/uploads/2017/05/Ethiopian-Food-beyaynet.jpg',
    desc: `በያይነት፥ ምንድነው መብላት ሚፈልጉት? ሽሮ ፣ ምስር ፣ ክክ ፣ ፓስታ ፣ ቀይ ሥር ፣ ቲማቲም ቁርጥ ፣ ጎመን ፣ ድንች ፣ ሁሉንም በአንድ ላይ የያዘ ምርጥ የሀበሽ ምግብ።`,
  },
  {
    id: 3,
    title: 'አርጎ',
    category: 'የሚጠጣ',
    price: 64.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmj_2kYhqF7f_md94h25iFiYcyhYrJKDMl8g&s',
    desc: `ከንፁ የላም ወተት የተዘጋጀ እርጎ ፤ ተፈጥሯዊ ይዘቱን እንደ ጠበቀ የተዘጋጀ።`,
  },
  {
    id: 4,
    title: 'ፉል',
    category: 'ቁርስ',
    price: 89.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXZevwUqKkdq7lQSwiL2GHV1c7Umsudfsk2A&s',
    desc: `የተከካ ባቄላ ፉል ከቅቤና በቤት ከተዘጋጀ ቅመማ ቅመም በፍቅርና በእንክንብካቤ የተዘጋጀ ምርጥ ፉል።`,
  },
  {
    id: 5,
    title: 'ሶያ',
    category: 'ምሳ',
    price: 109.99,
    img: 'https://i.ytimg.com/vi/LGsdnl5KdJ0/sddefault.jpg',
    desc: `ሶያ ፤ ከአኩሪ ዐተር ከሚዘጋጀ ሶያ የተዘጋጅ ምርጥ የጾም ምግም። በተለያየ አይነትና አቀራረብ የሚዘጋጅ።`,
  },
  {
    id: 6,
    title: 'አጥሚት',
    category: 'የሚጠጣ',
    price: 18.99,
    img: 'https://i.ytimg.com/vi/uTyTyej9s2Y/maxresdefault.jpg',
    desc: `በቤት የተዘጋጀ ቆንጆ የአጃ አጥሚት ፥ ተፈጥሯዊ ይዘቱን ሳይለቅ በጥንቃቄ የተዘጋጀ።`,
  },
  {
    id: 7,
    title: 'ጨጨብሳ',
    category: 'ቁርስ',
    price: 139.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUo1CxcWykhImfNeIy3xzsw0AVyKaNl8r2zw&s',
    desc: `የጤፍ ፤ የስንዴ ፤ የፊርኖ ዱኬት ጨጨብሳ ፣ በማር ፤ ብቅቤ ፤ እንዲሁም ስፔሻል ጨጨብሳ።`,
  },
  {
    id: 8,
    title: 'አንጮቴ',
    category: 'ምሳ',
    price: 129.99,
    img: 'https://img.sewasew.com/definitions/9b114e8571844bb8a0f4805a3a8a1508_406_270',
    desc: `አንጮቴ ፥ በደቡብ-ምዕራብ ሽዋ በስፋት የሚዘወተር የጾም ባህላዊ ምግብ። አንጮቴ ከሚባል ስራስር የሚዘጋጅ ባህላዊ ምግብ። `,
  },
  {
    id: 9,
    title: 'ሾርባ',
    category: 'የሚጠጣ',
    price: 16.99,
    img: 'https://ebtshopper.com/wp-content/uploads/2021/01/Callaway_BeanVegSoup.jpg',
    desc: `የተለያዩ የምግብ ግብአቶች አንደነ ድንች ፣ ካሮት ፣ ምኮሮኒ ፣ ሽንኩርት እና ሌሎችን በአንድነት የያዘ ፈሳሽ ምግብ። `,
  },

];
export default menu;
