const menu = {
  amharic: [
    {
      id: 1,
      title: 'እንጀራ ፍርፍር',
      category: 'ቁርስ',
      price: 119.99,
      img: 'https://queenshebabakery.com/wp-content/uploads/2024/10/photo_2024-10-15_08-50-06.jpg',
      desc: `ምርጥ የሀገርኛ ፍርፍር ፥ ከንጹ እንጀራና በቤት ከተዘጋጁ ቅመሞች በእናትነት ፍቅር እና እንክብካቤ የተዘጋጀ።`,
    },
    {
      id: 2,
      title: 'አይነት',
      category: 'ምሳ',
      price: 139.99,
      img: 'https://yaredzemainternationalhotelaxum.com/wp-content/uploads/2017/05/Ethiopian-Food-beyaynet.jpg',
      desc: `በያይነት፥ ምንድነው መብላት ሚፈልጉት? ሽሮ ፣ ምስር ፣ ክክ ፣ ፓስታ ፣ ቀይ ሥር ፣ ቲማቲም ቁርጥ ፣ ጎመን ፣ ድንች ፣ ሁሉንም በአንድ ላይ የያዘ ምርጥ የሀበሽ ምግብ።`,
    },
    {
      id: 3,
      title: 'አርጎ',
      category: 'የሚጠጣ',
      price: 64.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmj_2kYhqF7f_md94h25iFiYcyhYrJKDMl8g&s',
      desc: `ከንፁ የላም ወተት የተዘጋጀ እርጎ ፤ ተፈጥሯዊ ይዘቱን እንደ ጠበቀ የተዘጋጀ።`,
    },
    {
      id: 4,
      title: 'ፉል',
      category: 'ቁርስ',
      price: 89.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXZevwUqKkdq7lQSwiL2GHV1c7Umsudfsk2A&s',
      desc: `የተከካ ባቄላ ፉል ከቅቤና በቤት ከተዘጋጀ ቅመማ ቅመም በፍቅርና በእንክንብካቤ የተዘጋጀ ምርጥ ፉል።`,
    },
    {
      id: 5,
      title: 'ሶያ',
      category: 'ምሳ',
      price: 109.99,
      img: 'https://i.ytimg.com/vi/LGsdnl5KdJ0/sddefault.jpg',
      desc: `ሶያ ፤ ከአኩሪ ዐተር ከሚዘጋጀ ሶያ የተዘጋጅ ምርጥ የጾም ምግም። በተለያየ አይነትና አቀራረብ የሚዘጋጅ።`,
    },
    {
      id: 6,
      title: 'አጥሚት',
      category: 'የሚጠጣ',
      price: 18.99,
      img: 'https://i.ytimg.com/vi/uTyTyej9s2Y/maxresdefault.jpg',
      desc: `በቤት የተዘጋጀ ቆንጆ የአጃ አጥሚት ፥ ተፈጥሯዊ ይዘቱን ሳይለቅ በጥንቃቄ የተዘጋጀ።`,
    },
    {
      id: 7,
      title: 'ጨጨብሳ',
      category: 'ቁርስ',
      price: 139.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUo1CxcWykhImfNeIy3xzsw0AVyKaNl8r2zw&s',
      desc: `የጤፍ ፤ የስንዴ ፤ የፊርኖ ዱኬት ጨጨብሳ ፣ በማር ፤ ብቅቤ ፤ እንዲሁም ስፔሻል ጨጨብሳ።`,
    },
    {
      id: 8,
      title: 'አንጮቴ',
      category: 'ምሳ',
      price: 129.99,
      img: 'https://img.sewasew.com/definitions/9b114e8571844bb8a0f4805a3a8a1508_406_270',
      desc: `አንጮቴ ፥ በደቡብ-ምዕራብ ሽዋ በስፋት የሚዘወተር የጾም ባህላዊ ምግብ። አንጮቴ ከሚባል ስራስር የሚዘጋጅ ባህላዊ ምግብ። `,
    },
    {
      id: 9,
      title: 'ሾርባ',
      category: 'የሚጠጣ',
      price: 64.99,
      img: 'https://ebtshopper.com/wp-content/uploads/2021/01/Callaway_BeanVegSoup.jpg',
      desc: `የተለያዩ የምግብ ግብአቶች አንደነ ድንች ፣ ካሮት ፣ ምኮሮኒ ፣ ሽንኩርት እና ሌሎችን በአንድነት የያዘ ፈሳሽ ምግብ። `,
    },
  ],
  oromo: [

    // for afan oromo language
    {
      id: 1,
      title: 'firfirii buddeenaa',
      category: 'ciree',
      price: 119.99,
      img: 'https://queenshebabakery.com/wp-content/uploads/2024/10/photo_2024-10-15_08-50-06.jpg',
      desc: `Firfira biyyaa filatamaa, buddeena qulqulluu fi mi’eessituu manatti qophaa’an irraa, jaalala fi kunuunsa haadhummaatiin kan qophaa’e.`,
    },
    {
      id: 2,
      title: 'beyaaynatii',
      category: 'laaqana',
      price: 139.99,
      img: 'https://yaredzemainternationalhotelaxum.com/wp-content/uploads/2017/05/Ethiopian-Food-beyaynet.jpg',
      desc: `Beyaaynatii, maal nyaachuu barbaaddu? Shiroo, misira, kikkii, paastaa, hundee diimaa, timaatima murame, raafuu, dinicha, kan hunda of keessatti qabatu nyaata Habashaa keessaa isa filatamaa.`,
    },
    {
      id: 3,
      title: 'itittuu',
      category: 'waan dhugamu',
      price: 64.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmj_2kYhqF7f_md94h25iFiYcyhYrJKDMl8g&s',
      desc: `Itittuu aannan sa'a qulqulluu irraa qophaa'e; akka qabiyyee uumamaa isaa eegatetti kan qophaa'edha.`,
    },
    {
      id: 4,
      title: 'Fuulii',
      category: 'ciree',
      price: 89.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXZevwUqKkdq7lQSwiL2GHV1c7Umsudfsk2A&s',
      desc: `baaqelaa duudaa ykn daakuudhaan zayitii/dhadhaa fi mi'eessituu mana keessatti qophaa'een, jaalalaa fi kunuunsaan kan qophaa'e ful gaarii (filatamaa).`,
    },
    {
      id: 5,
      title: 'Sooyaa',
      category: 'laaqana',
      price: 109.99,
      img: 'https://i.ytimg.com/vi/LGsdnl5KdJ0/sddefault.jpg',
      desc: `Soya; nyaata soomaa gaarii atarbarraqee irraa qophaa'u. Gosa fi bifa garagaraan kan qophaawu.`,
    },
    {
      id: 6,
      title: 'Mooqa',
      category: 'waan dhugamu',
      price: 18.99,
      img: 'https://i.ytimg.com/vi/uTyTyej9s2Y/maxresdefault.jpg',
      desc: `Mooqa furnoo ykn Ajaa mi’aawaa manatti qophaa’e, qulqullina uumamaa isaa osoo hin gadhiisin of-eeggannoon kan qophaa’e.`,
    },
    {
      id: 7,
      title: 'cacabsaa',
      category: 'ciree',
      price: 139.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUo1CxcWykhImfNeIy3xzsw0AVyKaNl8r2zw&s',
      desc: `Caccabsaa qamadii (xaafii), daakuu fi laallaa, damma, dhadhaa akkasumas caccabsaa addaa.`,
    },
    {
      id: 8,
      title: 'anchootee',
      category: 'laaqana',
      price: 129.99,
      img: 'https://img.sewasew.com/definitions/9b114e8571844bb8a0f4805a3a8a1508_406_270',
      desc: `Ancooteen naannoo Shawaa Kibba-Lixaa keessatti nyaata aadaa yeroo soomanaatti bal'inaan beekamuudha. Hiddi Ancoote jedhamu kun nyaata aadaa lafarra ba'u (srasir) irraa qophaa'uudha.`,
    },
    {
      id: 9,
      title: 'Shorbaa',
      category: 'waan dhugamu',
      price: 64.99,
      img: 'https://ebtshopper.com/wp-content/uploads/2021/01/Callaway_BeanVegSoup.jpg',
      desc: `Nyaata dhangala'aa wantoota nyaataaf oolan kan akka dinichaa, kaarotii, maakaroonii, qullubbii fi kan biroo walitti qabatee qophaa'u.`,
    },
  ],
  english: [

    // for english language
    {
      id: 1,
      title: 'Ferfer',
      category: 'breakfast',
      price: 119.99,
      img: 'https://queenshebabakery.com/wp-content/uploads/2024/10/photo_2024-10-15_08-50-06.jpg',
      desc: `The best traditional firfir — prepared with fresh injera and homemade spices with motherly love and care.`,
    },
    {
      id: 2,
      title: 'Beyaynet',
      category: 'lunch',
      price: 139.99,
      img: 'https://yaredzemainternationalhotelaxum.com/wp-content/uploads/2017/05/Ethiopian-Food-beyaynet.jpg',
      desc: `Beyaynet, what would you like to eat? Shiro, lentils, kik, pasta, beetroot, chopped tomatoes, cabbage, potatoes; the ultimate Habesha (Ethiopian) meal that has it all on one platter.`,
    },
    {
      id: 3,
      title: 'Yogurt',
      category: 'shakes',
      price: 64.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmj_2kYhqF7f_md94h25iFiYcyhYrJKDMl8g&s',
      desc: `Yogurt prepared from pure cow's milk; prepared while preserving its natural content.`,
    },
    {
      id: 4,
      title: 'Ful',
      category: 'breakfast',
      price: 89.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXZevwUqKkdq7lQSwiL2GHV1c7Umsudfsk2A&s',
      desc: `Mashed fava bean ful with butter and homemade spices, the best ful prepared with love and care.`,
    },
    {
      id: 5,
      title: 'Soy',
      category: 'lunch',
      price: 109.99,
      img: 'https://i.ytimg.com/vi/LGsdnl5KdJ0/sddefault.jpg',
      desc: `Soy; an excellent vegan/fasting dish made from soybeans. Prepared in various types and presentations.`,
    },
    {
      id: 6,
      title: 'Oat Porridge',
      category: 'shakes',
      price: 18.99,
      img: 'https://i.ytimg.com/vi/uTyTyej9s2Y/maxresdefault.jpg',
      desc: `Beautiful homemade oat porridge, carefully prepared without losing its natural goodness.`,
    },
    {
      id: 7,
      title: 'Chechebsa',
      category: 'breakfast',
      price: 139.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUo1CxcWykhImfNeIy3xzsw0AVyKaNl8r2zw&s',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Anchote',
      category: 'lunch',
      price: 129.99,
      img: 'https://img.sewasew.com/definitions/9b114e8571844bb8a0f4805a3a8a1508_406_270',
      desc: `Teff, wheat, and white flour chechebsa, with honey, butter, as well as special chechebsa.`,
    },
    {
      id: 9,
      title: 'Shorba',
      category: 'shakes',
      price: 64.99,
      img: 'https://ebtshopper.com/wp-content/uploads/2021/01/Callaway_BeanVegSoup.jpg',
      desc: `A liquid food containing various ingredients together, such as potatoes, carrots, macaroni, onion, and others.`,
    },
  ]


};

export default menu;
